server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: social_network
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: social
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/social"
    username: qwe123
    password: qwe123